In [47]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from scipy.optimize import curve_fit
import altair as alt

In [111]:
data_path = "RLC-02.csv" #Resistência (300)

df = pd.read_csv(data_path)

def func(t, Voff, V_max, alfa, omega): #Função que teóricamente representa nossos dados
    beta = np.sqrt(omega**2 - alfa**2)
    return V_max * np.exp(-alfa * t) * (np.cos(beta * t) + (alfa / beta) * np.sin(beta * t)) + Voff

#Selecionando apenas a parte da caída
id_min, id_max = 0, 300
tempo = df['Time'].loc[id_min+250:id_max + 1].values
ddv = df['U_b'].loc[id_min+250:id_max + 1].values

#Ajustando tempo inicial = 0
tempo = tempo - tempo[0]

#Argumentos iniciais para o fit
arg = [1.864,-3.867,79358.7,115135.44]

#fit e matriz de covariância
par_optimize, cov = curve_fit(
        func, tempo, ddv, p0=[arg[0], arg[1], arg[2],arg[3]], maxfev=100000
    )

#Dados importantes
voff,vmax,alfa,omega = par_optimize

#Criando Função com parâmetros ajustados
x_data = np.linspace(tempo[0],tempo[-1],1000)
y_data = func(x_data,voff,vmax,alfa,omega)

#DataFrame que representa o ajuste
data = pd.DataFrame()
data["Time"] = x_data * 1000 #escala para ms
data["U_b"] = y_data

#DataFrame que representa os pontos
pontos = pd.DataFrame()
pontos["Time"] = tempo * 1000
pontos["U_b"] = ddv



q =alt.Chart(data).mark_line(color="red").encode(
    x = "Time",
    y = "U_b"
)

p =alt.Chart(pontos).mark_circle().encode(
    alt.X("Time",title = "Tempo (ms)"),
    alt.Y("U_b", title = "Volts (V)")
)
df["Time"] -= df["Time"][0]
df["Time"]*= 1000
j = alt.Chart(df).mark_line().encode(
    alt.X("Time", title = "Tempo (ms)"),
    alt.Y("U_b", title = "Tensão (V)")
)

# Subscrevendo em um arquivo
with open("data_rlc(300).txt", "w") as f:
    # Escrevendo a matriz de covariância
    f.write("Matriz de Covariância:\n")
    f.write(f"{cov}\n\n")
    
    # Escrevendo as incertezas
    f.write("Incertezas:\n")
    f.write(f"Voff: {np.sqrt(np.diag(cov))[0]}\n")
    f.write(f"V_max: {np.sqrt(np.diag(cov))[1]}\n")
    f.write(f"alpha: {np.sqrt(np.diag(cov))[2]}\n")
    f.write(f"omega: {np.sqrt(np.diag(cov))[3]}\n\n")
    
    # Escrevendo os valores calculados
    f.write("Valores calculados:\n")
    f.write(f"Voff: {voff}\n")
    f.write(f"V_max: {vmax}\n")
    f.write(f"alpha: {alfa}\n")
    f.write(f"omega: {omega}\n")

q+p


alt.Chart(...)

In [103]:
data_path = "RLC-01.csv" #Resistência (0)

df = pd.read_csv(data_path)

def func(t, Voff, V_max, alfa, omega): 
    beta = np.sqrt(omega**2 - alfa**2)
    return V_max * np.exp(-alfa * t) * (np.cos(beta * t) + (alfa / beta) * np.sin(beta * t)) + Voff

id_min, id_max = 0, 40
tempo = df['Time'].loc[id_min:id_max + 1].values
ddv = df['U_b'].loc[id_min:id_max + 1].values
arg = [-2,3.9,46000,112673]

tempo = tempo - tempo[0]

par_optimize, cov = curve_fit(
        func, tempo, ddv, p0=[arg[0], arg[1], arg[2],arg[3]], maxfev=100000
    )
print(par_optimize)
voff,vmax,alfa,omega = par_optimize
print(np.sqrt(np.diag(cov)))

x_data = np.linspace(tempo[0],tempo[-1],1000)
y_data = func(x_data,-2,3.9,46000,112673)

data = pd.DataFrame()
data["Time"] = x_data * 1000
data["U_b"] = y_data

pontos = pd.DataFrame()
pontos["Time"] = tempo * 1000
pontos["U_b"] = ddv



q =alt.Chart(data).mark_line(color="red").encode(
    x = "Time",
    y = "U_b"
)

p =alt.Chart(pontos).mark_circle().encode(
    alt.X("Time",title = "Tempo (ms)"),
    alt.Y("U_b", title = "Volts (V)")
)

12500,42500,72500
df["Time"] -= df["Time"][0]
df["Time"] *= 1000

j = alt.Chart(df).mark_line().encode(
    alt.X("Time", title = "Tempo (ms)"),
    alt.Y("U_b", title = "Tensão (V)")
)

q+p

with open("data_rlc(0).txt", "w") as f:
    # Escrevendo a matriz de covariância
    f.write("Matriz de Covariância:\n")
    f.write(f"{cov}\n\n")
    
    # Escrevendo as incertezas
    f.write("Incertezas:\n")
    f.write(f"Voff: {np.sqrt(np.diag(cov))[0]}\n")
    f.write(f"V_max: {np.sqrt(np.diag(cov))[1]}\n")
    f.write(f"alpha: {np.sqrt(np.diag(cov))[2]}\n")
    f.write(f"omega: {np.sqrt(np.diag(cov))[3]}\n\n")
    
    # Escrevendo os valores calculados
    f.write("Valores calculados:\n")
    f.write(f"Voff: {voff}\n")
    f.write(f"V_max: {vmax}\n")
    f.write(f"alpha: {alfa}\n")
    f.write(f"omega: {omega}\n")

q+p
j


[-2.01456777e+00  3.96887553e+00  4.65318041e+04  1.12690777e+05]
[2.61850574e-03 1.19273785e-02 3.21300366e+02 2.79640980e+02]


alt.Chart(...)

In [107]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from scipy.optimize import curve_fit

data_path = "RLC-03.csv"

df = pd.read_csv(data_path)

def func(t, Voff, V_max, alfa, omega):
    beta = np.sqrt(omega**2 - alfa**2)
    return V_max * np.exp(-alfa * t) * (np.cos(beta * t) + (alfa / beta) * np.sin(beta * t)) + Voff

id_min, id_max = 0, 300
tempo = df['Time'].loc[id_min+250:id_max + 1].values
ddv = df['U_b'].loc[id_min+250:id_max + 1].values
print(tempo)

tempo = tempo - tempo[0]

x_data = np.linspace(tempo[0],tempo[-1],1000)
y_data = func(x_data,-1.9147852867706756,3.7422431373048153,118630.13754571596,121430.1523736816)

data = pd.DataFrame()
data["Time"] = x_data*1000
data["U_b"] = y_data

pontos = pd.DataFrame()
pontos["Time"] = tempo*1000
pontos["U_b"] = ddv

q =alt.Chart(data).mark_line(color="red").encode(
    alt.X("Time",title = "Tempo (ms)"),
    alt.Y("U_b", title = "Tensão (V)")
)

p =alt.Chart(pontos).mark_circle().encode(
    alt.X("Time",title = "Tempo (ms)"),
    alt.Y("U_b", title = "Volts (V)")
)
df["Time"] -= df["Time"][0]
df["Time"] *= 1000
j = alt.Chart(df).mark_line().encode(
    alt.X("Time", title = "Tempo (ms)"),
    alt.Y("U_b", title = "Tensão (V)")
)
arg = [1.8,-3.7,113523,119291]

par_optimize, cov = curve_fit(
        func, tempo, ddv, p0=[arg[0], arg[1], arg[2],arg[3]], maxfev=100000
    )
print(par_optimize)
voff,vmax,alfa,omega = par_optimize
print(np.sqrt(np.diag(cov)))

with open("data_rlc(600).txt", "w") as f:
    # Escrevendo a matriz de covariância
    f.write("Matriz de Covariância:\n")
    f.write(f"{cov}\n\n")
    
    # Escrevendo as incertezas
    f.write("Incertezas:\n")
    f.write(f"Voff: {np.sqrt(np.diag(cov))[0]}\n")
    f.write(f"V_max: {np.sqrt(np.diag(cov))[1]}\n")
    f.write(f"alpha: {np.sqrt(np.diag(cov))[2]}\n")
    f.write(f"omega: {np.sqrt(np.diag(cov))[3]}\n\n")
    
    # Escrevendo os valores calculados
    f.write("Valores calculados:\n")
    f.write(f"Voff: {voff}\n")
    f.write(f"V_max: {vmax}\n")
    f.write(f"alpha: {alfa}\n")
    f.write(f"omega: {omega}\n")

q+p


[-0.0005   -0.000498 -0.000496 -0.000494 -0.000492 -0.00049  -0.000488
 -0.000486 -0.000484 -0.000482 -0.00048  -0.000478 -0.000476 -0.000474
 -0.000472 -0.00047  -0.000468 -0.000466 -0.000464 -0.000462 -0.00046
 -0.000458 -0.000456 -0.000454 -0.000452 -0.00045  -0.000448 -0.000446
 -0.000444 -0.000442 -0.00044  -0.000438 -0.000436 -0.000434 -0.000432
 -0.00043  -0.000428 -0.000426 -0.000424 -0.000422 -0.00042  -0.000418
 -0.000416 -0.000414 -0.000412 -0.00041  -0.000408 -0.000406 -0.000404
 -0.000402 -0.0004   -0.000398]
[-1.91478529e+00  3.74224314e+00  1.18630138e+05  1.21430152e+05]
[1.55957497e-03 4.89169990e-03 8.60190893e+02 4.35294037e+02]


alt.LayerChart(...)